modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
[[mods]]
modId = "rsrequestify"
version = "${file.jarVersion}"
displayName = "RSRequestify"
authors = "Buuz135"
description = "Keep a stock of your craftables"

[[dependencies.rsrequestify]]
    modId="refinedstorage"
    type="required"
    versionRange = "[1.12.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rsrequestify]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,)"
    ordering="NONE"
    side="BOTH"
